name: cbn_mcp
description: MCP server for Central Bank of Nigeria (CBN) API integration.
version: 1.0.0
repository: https://github.com/chiziaruhoma/cbn_mcp
homepage: https://github.com/chiziaruhoma/cbn_mcp
issue_tracker: https://github.com/chiziaruhoma/cbn_mcp/issues
publish_to: none

executables:
  cbn_mcp:

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  mcp_server_dart:
    git: 
      url: https://github.com/zfinix/mcp_server_dart.git
      ref: bd4e14626da34a63382eb735157a485af441b3ec
  

  http: ^1.2.0
  dio: ^5.4.0
  logging: ^1.3.0
  dart_mappable: ^4.2.2
  dartz: ^0.10.1
  dartx: ^1.2.0
  logger: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.2.3
  json_serializable: ^6.7.1
  lints: ^6.0.0
  test: ^1.25.6
  mockito: ^5.4.4
